# Generated by Django 4.2.2 on 2023-06-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название', max_length=255)),
                ('description', models.TextField(default='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.URLField(blank=True, null=True)),
                ('image_1', models.URLField(blank=True, null=True)),
                ('image_2', models.URLField(blank=True, null=True)),
                ('image_3', models.URLField(blank=True, null=True)),
                ('image_4', models.URLField(blank=True, null=True)),
                ('genres', models.ManyToManyField(to='store.genre')),
            ],
        ),
    ]
