# Generated by Django 4.2.2 on 2023-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_1',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение 1(слайдер)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_2',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение 1(слайдер)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_3',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение 1(слайдер)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_4',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение 1(слайдер)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='Название', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Видео(ссылка)'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название жанра'),
        ),
    ]
