# Generated by Django 4.2.2 on 2023-06-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_game_options_alter_game_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_2',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение 2(слайдер)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_3',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение 3(слайдер)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_4',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение 4(слайдер)'),
        ),
    ]
