# Generated by Django 4.2.2 on 2023-06-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_game_image_2_alter_game_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster_height',
            field=models.PositiveIntegerField(blank=True, default='300', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='poster_width',
            field=models.PositiveIntegerField(blank=True, default='300', editable=False, null=True),
        ),
    ]
