# Generated by Django 4.2.2 on 2023-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_game_poster_height_game_poster_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='poster_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
    ]
