# Generated by Django 4.2.2 on 2023-06-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подписка'),
        ),
    ]
