# Generated by Django 4.2.2 on 2023-06-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_profile_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image_4',
        ),
        migrations.AddField(
            model_name='game',
            name='download',
            field=models.URLField(default='https://track.wg-aff.com/click?pid=700&offer_id=24'),
        ),
    ]
