# Generated by Django 4.2.2 on 2023-06-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_game_image_1_remove_game_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='download',
            field=models.URLField(default='https://track.wg-aff.com/click?pid=700&offer_id=24', verbose_name='Ссылка на установку'),
        ),
    ]
