# Generated by Django 4.2.2 on 2023-06-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
