# Generated by Django 4.2.2 on 2023-06-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_game_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='store.genre', verbose_name='Жанры'),
        ),
    ]
