# Generated by Django 4.2.2 on 2023-06-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_game_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='store.game')),
            ],
        ),
    ]
