# Generated by Django 4.2.2 on 2023-06-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_gamecount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameCount',
        ),
    ]
